# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '6bb69dc1-ef0f-4bea-bcdc-580a2ad5e6e4'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'test'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/fefogonzalez/RepoAzure/main/test_lucas/newdebian.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/fefogonzalez/RepoAzure/main/test_lucas/newdebian.parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'Debian-test'
    
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '6bb69dc1-ef0f-4bea-bcdc-580a2ad5e6e4'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'test'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/fefogonzalez/RepoAzure/main/test_lucas/loadbalancer-template.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/fefogonzalez/RepoAzure/main/test_lucas/loadbalancer-template.parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'LoadBalancer'